
# react-native-google-place-picker dependencies

pod 'GooglePlacePicker', '= 2.0.1'
pod 'GooglePlaces', '= 2.0.1'
pod 'GoogleMaps', '= 2.0.1'



# Add new pods below this line
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

pod 'react-native-video', :path => '../node_modules/react-native-video'









pod 'RNScreens', :path => '../node_modules/react-native-screens'


pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'



pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'




pod 'RNSVG', :path => '../node_modules/react-native-svg'

pod 'RNShare', :path => '../node_modules/react-native-share'

pod 'react-native-maps', :path => '../node_modules/react-native-maps'

